on:
  push:
    branches:
    - main

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    # Installs Node and the npm packages saved in your package.json file in the build
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
      with:
        node-version: 18.x
        
    - name: install ADF Utilities package
      run: npm install
      working-directory: ${{ github.workspace }}/build  # (1) provide the folder location of the package.json file
        
    # Validates all of the Data Factory resources in the repository.
    - name: Validate
      run: >
        npm run build validate
        ${{ github.workspace }}/
        /subscriptions/5c1e20f0-f569-475e-92f7-8305be4cfcac/resourceGroups/rg_devop/providers/Microsoft.DataFactory/factories/adfdevop2025v1
